# Generated by Django 5.0.1 on 2024-02-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("price", models.FloatField(verbose_name="Цена")),
                ("image", models.URLField(verbose_name="Изображение")),
                ("release_date", models.DateTimeField(verbose_name="Дата выхода")),
                ("lte_exists", models.BooleanField(default=False)),
                ("slug", models.SlugField(verbose_name="Слаг")),
            ],
        ),
    ]
